# Site settings
title: Guide to GDPR
description: A Cheat Sheet for App Developers
baseurl: "/apps-gdpr-guide" # the subpath of your site, e.g. /blog
url: "kasnder.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

email: gdpr@kollnig.net
github_page: https://github.com/kasnder/app-dev-privacy-guidelines
pdf_file: https://kasnder.github.io/apps-gdpr-guide/pdf/guidelines.pdf

exclude: ['background.md', 'guidelines.md', 'services.md', 'Gemfile*', 'src' , 'node_modules']
