# Site settings
title: Guide to GDPR for App Developers
description: Authored by an App Developer
#baseurl: "/apps-gdpr-guide" # the subpath of your site, e.g. /blog
url: "gdpr4devs.com" # the base hostname & protocol for your site

email: gdpr@kollnig.net
github_page: https://github.com/kasnder/apps-gdpr-guide
pdf_file: https://gdpr4devs.com/guidelines.pdf

exclude: ['background.md', 'guidelines.md', 'services.md', 'Gemfile*', 'src' , 'node_modules']
