# Site settings
title: Guide to GDPR for App Developers
description: Written by an App Developer
#baseurl: "/apps-gdpr-guide" # the subpath of your site, e.g. /blog
url: "kasnder.github.io/gdpr4devs" # the base hostname & protocol for your site

email: gdpr@kollnig.net
github_page: https://github.com/kasnder/gdpr4devs
pdf_file: https://kasnder.github.io/gdpr4devs/guidelines.pdf

exclude: ['background.md', 'guidelines.md', 'services.md', 'Gemfile*', 'src' , 'node_modules']
